export const dataEvaluate = [
  {
    id: 1,
    imgE: 'https://quanlykho.vn/wp-content/uploads/2019/11/quay-ba-thuong-co-khach-san-lon.png',
    avt: 'https://kinhtechungkhoan.vn/stores/news_dataimages/thuydung/052022/20/11/4451_SharkBinh.jpg?rt=20220520114454',
    name: 'Shark Bình',
    date: '7/06/2022',
    premiumTwin: 'Sala Đà Nẵng Beach',
    time: '2 ngày 2 đêm',
    evaluate: 'Tuyệt vời, trải nghiệm tuyệt vời',
    coment: 'Bữa ăn sáng phong phú, phòng đẹp.Thiết kế phòng hiện đại, sáng tạo - Hệ thống nước mạnh dù mình ở tầng cao nhất - Có chiến dịch bảo vệ môi trường - Dọn phòng nhanh chóng - Wifi ổn định, tivi nhiều kênh và rõ nét - Có hầm đỗ xe tiện nghi - Có hồ bơi và quầy bar - Check out nhanh chóng - Toàn bộ nhân viên đều rất trẻ',
    point: '9.9',
    cmt: 'Tuyệt vời',
  },

  {
    id: 2,
    imgE: 'https://vcdn-dulich.vnecdn.net/2020/09/11/Khach-san-tim-huong-di-moi-3-2389-1599800270.jpg',
    avt: 'https://baohay.vn/wp-content/uploads/2019/08/nguyen-xuan-phu.jpg',
    name: 'Shark Phú',
    date: '11/05/2022',
    premiumTwin: 'InterContinental Da Nang',
    time: '2 ngày 1 đêm',
    evaluate: 'Khách sạn Hilton Đà Nẵng',
    coment: 'Cung cấp các lựa chọn ăn uống tuyệt hảo như La Maison 1888 danh tiếng, InterContinental Danang Sun Peninsula Resort đem đến nơi lánh mình sang trọng với bãi biển riêng, hồ bơi lớn ngoài trời và spa. Trải nghiệm ăn uống bên bờ biển thoải mái, hãy ghé vào nhà hàng Barefoot và nếm thử các loại thịt nướng thơm ngon cũng như hải sản tươi ngon kết hợp với cocktail và rượu vang',
    point: '9.7',
    cmt: 'Tuyệt vời',
  },
  {
    id: 3,
    imgE: 'https://tuyensinhcaodangdulich.edu.vn/upload/con-gai-co-nen-hoc-nganh-quan-tri-khach-san-nha-hang-1.jpg',
    avt: 'https://galaxylands.com.vn/wp-content/uploads/2022/03/shark-hung-tap-doan-cen-group.jpg',
    name: 'Shark Hưng',
    date: '22/07/2022',
    time: '3 ngày 2 đêm',
    premiumTwin: 'Florida Nha Trang',
    evaluate: 'Dịch vụ tốt, chăm sóc khách hàng tận tâm',
    coment: 'Tọa lạc tại thành phố Nha Trang, cách Bãi biển Nha Trang 700 m, Florida Nha Trang Hotel cung cấp chỗ nghỉ có nhà hàng, chỗ đỗ xe riêng miễn phí, hồ bơi ngoài trời và trung tâm thể dục.Khách sạn phục vụ bữa sáng kiểu lục địa và tự chọn hàng ngày. Florida Nha Trang Hotel có sân chơi cho trẻ em. Du khách có thể thuê xe máy hoặc xe hơi để khám phá khu vực, sử dụng trung tâm dịch vụ doanh nhân hoặc đọc báo có sẵn trong khuôn viên. Các điểm tham quan nổi tiếng gần chỗ nghỉ bao gồm Bảo tàng Alexandre Yersin, trung tâm thương mại Nha Trang Centre và Chợ Đầm.',
    point: '9.6',
    cmt: 'Tuyệt vời',
  },
  {
    id: 4,
    imgE: 'https://www.hoteljob.vn/files/Ni%20-%20%E1%BA%A2nh%20HTJ/2018/Th%C3%A1ng%206/BS%20t6/Tieu-chuan-dich-vu-khach-san-5-sao-01.jpg',
    avt: 'https://bstyle.vn/wp-content/uploads/2019/04/shark-nguyen-thanh-viet-1.jpg',
    name: 'Shark Việt',
    date: '15/06/2022',
    premiumTwin: 'Cereja Hotel ',
    time: '2 ngày',
    evaluate: 'Đồ ăn ngon, có các trò chơi giải trí thú vị',
    coment: 'Khách sạn không chỉ giúp bạn có được chỗ nghỉ ngơi thoải mái, thoáng mát với giá phòng rẻ mà còn rất nhiều tiện ích dịch vụ chất lượng. Vị trí và phương tiện di chuyển Khách sạn có địa chỉ tại: Phân khu chức năng 7, Khu du lịch Hồ Tuyền Lâm, Phường 3, Tp. Đà Lạt, tỉnh Lâm Đồng. Với vị cách hồ Tuyền Lâm 3km bạn có thể dễ dàng di chuyển đến khám phá cảnh đẹp tại thành phố Đà Lạt. Đây là khách sạn đạt tiêu chuẩn 4 sao có phong cách thiết kế tinh tế, hiện đại. Đây là không gian nghỉ dưỡng lý tưởng cho mọi tầng lớp xã hội. Mỗi tòa biệt thự của khu nghỉ dưỡng này đều mang đến cho du khách một không gian khác biệt, đáp ứng linh hoạt các nhu cầu của quý khách.',
    point: '9.8',
    cmt: 'Tuyệt vời',
  },
  {
    id: 5,
    imgE: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxc6Y5OcGv0aA2S-HBAgHNY_p-lxPSFY05VQ&usqp=CAU',
    avt: 'https://cafefcdn.com/thumb_w/650/203337114487263232/2021/7/23/photo1627030924824-16270309250651512805054.jpg',
    name: 'Shark Liên',
    date: '15/06/2022',
    premiumTwin: 'New World Phú Quốc',
    time: '3 ngày, 2 đêm',
    evaluate: 'Khách sạn xanh, sạch đẹp, thân thiện với khách hàng',
    coment: 'mang vẻ đẹp của làng chài ven biển. Đây cũng là nơi được mệnh danh là kho báu thiên nhiên miền nhiệt đới, nơi đánh thức các giác quan của mọi du khách với biển xanh, cát trắng, hoà cùng nét mộc mạc và giản dị trong từng không gian nghỉ dưỡng. Cho dù bạn đang tìm kiếm một chốn dừng chân bình yên giữa thiên nhiên, hay nơi ẩn mình thư thái bên cảnh biển tuyệt đẹp mà không mất đi sự gắn kết thân thuộc với gia đình và bạn bè, thì những căn biệt thự đa dạng tại New World Phú Quốc chắc hẳn sẽ không làm bạn thất vọng. Đằng sau mỗi cánh cửa là một thế giới thư giãn đầy cảm hứng mở ra những xúc cảm diệu kỳ. Sự màu nhiệm của thiên nhiên hòa cùng không khí trong lành là thời điểm thích hợp cho các hoạt động ngoài trời, các môn thể thao dưới nước, các liệu trình chăm sóc cơ thể, hay bài tập yoga thư giãn. Với đa dạng các khu vực vui chơi và giải trí',
    point: '9.8',
    cmt: 'Tuyệt vời',
  },
]