export const dataTopPosts = [
  {
    id: 1,
    img2: 'https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2017/08/ban-dao-son-tra-da-nang.jpg',
    title2:'Du Lịch Bán Đảo Sơn Trà – Kinh Nghiệm & Hướng Dẫn Chi Tiết',
    text2: 'Điểm du lịch nào có nhiều cảnh quan đẹp, món ăn ngon, đáng đến nhất là điều mà nhiều du khách trong và ngoài nước quan tâm khi lên kế hoạch khám phá Việt Nam. Review 20+ địa điểm du lịch nổi tiếng nhất đang thu hút đông đảo khách tham quan.Việt Nam có vô vàn điểm du lịch hấp dẫn. Du lịch miền...',
  },
  { id: 2,
    img2: 'https://cdn.reatimes.vn/mediav2/upload/userfiles2021/images/luongkim/04-4/Tiem-nang-do-thi-hai-chau-da-nang%20(2).jpg',
    title2:'Cảnh đẹp Hải Châu từ A - Z',
    text2: 'Điểm du lịch nào có nhiều cảnh quan đẹp, món ăn ngon, đáng đến nhất là điều mà nhiều du khách trong và ngoài nước quan tâm khi lên kế hoạch khám phá Việt Nam. Review 20+ địa điểm du lịch nổi tiếng nhất đang thu hút đông đảo khách tham quan.Việt Nam có vô vàn điểm du lịch hấp dẫn. Du lịch miền...',
  },
  
  { id:3,
    img2: 'https://vietnaminsider.vn/wp-content/uploads/2022/03/e5.jpg',
    title2:'Biển Nha Trang lộng lẫy giữa những ngày hè ',
    text2: 'Điểm du lịch nào có nhiều cảnh quan đẹp, món ăn ngon, đáng đến nhất là điều mà nhiều du khách trong và ngoài nước quan tâm khi lên kế hoạch khám phá Việt Nam. Review 20+ địa điểm du lịch nổi tiếng nhất đang thu hút đông đảo khách tham quan.Việt Nam có vô vàn điểm du lịch hấp dẫn. Du lịch miền...',
  },
  {
    id: 4,
    img2: 'https://flytime.vn/upload/img/products/08ae65742cda01e85a345a92e2744a2b.gif',
    title2:'Check-In tại Phú Quốc, hòn đảo của thiên nhiên tráng lệ và bắt mắt',
    text2: 'Điểm du lịch nào có nhiều cảnh quan đẹp, món ăn ngon, đáng đến nhất là điều mà nhiều du khách trong và ngoài nước quan tâm khi lên kế hoạch khám phá Việt Nam. Review 20+ địa điểm du lịch nổi tiếng nhất đang thu hút đông đảo khách tham quan.Việt Nam có vô vàn điểm du lịch hấp dẫn. Du lịch miền...',
  },
  { id: 5,
    img2: 'https://photo-cms-plo.zadn.vn/w850/Uploaded/2022/bpcbzqvp/2020_03_04/binh-minh-da-lat-dep-nap-long-1_kabt.jpg',
    title2:'Đà Lạt trải nghiệm 4 mùa trong từng khoảng khắc',
    text2: 'Điểm du lịch nào có nhiều cảnh quan đẹp, món ăn ngon, đáng đến nhất là điều mà nhiều du khách trong và ngoài nước quan tâm khi lên kế hoạch khám phá Việt Nam. Review 20+ địa điểm du lịch nổi tiếng nhất đang thu hút đông đảo khách tham quan.Việt Nam có vô vàn điểm du lịch hấp dẫn. Du lịch miền...',
  },
]
